import { createAction } from '@reduxjs/toolkit';
import { STATE_REDUCER_KEY } from './constants';

export const ACTION_TYPES = {

  VERIFY_LOGIN: `${STATE_REDUCER_KEY}/VERIFY_LOGIN`,
  VERIFY_LOGIN_REQUEST: `${STATE_REDUCER_KEY}/VERIFY_LOGIN_REQUEST`,
  VERIFY_LOGIN_SUCCESS: `${STATE_REDUCER_KEY}/VERIFY_LOGIN_SUCCESS`,
  VERIFY_LOGIN_FAILURE: `${STATE_REDUCER_KEY}/VERIFY_LOGIN_FAILURE`,

  FORGOT_PASSWORD: `${STATE_REDUCER_KEY}/FORGOT_PASSWORD`,
  FORGOT_PASSWORD_REQUEST: `${STATE_REDUCER_KEY}/FORGOT_PASSWORD_REQUEST`,
  FORGOT_PASSWORD_SUCCESS: `${STATE_REDUCER_KEY}/FORGOT_PASSWORD_SUCCESS`,
  FORGOT_PASSWORD_FAILURE: `${STATE_REDUCER_KEY}/FORGOT_PASSWORD_FAILURE`

};

export const verifyLogin = createAction(ACTION_TYPES.VERIFY_LOGIN);
export const forgotPassword = createAction(ACTION_TYPES.FORGOT_PASSWORD);


