import { createAction } from '@reduxjs/toolkit';
import { STATE_REDUCER_KEY } from './constants';

export const ACTION_TYPES = {
  FETCH_COUNTRY: `${STATE_REDUCER_KEY}/FETCH_COUNTRY`,
  FETCH_COUNTRY_REQUEST: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_REQUEST`,
  FETCH_COUNTRY_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_SUCCESS`,
  FETCH_COUNTRY_FAILURE: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_FAILURE`,

  CREATE_ORGANIZATION_DETAILS: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS`,
  CREATE_ORGANIZATION_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_REQUEST`,
  CREATE_ORGANIZATION_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_SUCCESS`,
  CREATE_ORGANIZATION_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_FAILURE`,

  UPDATE_ORGANIZATION_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_ORGANIZATION_DETAILS`,
  UPDATE_ORGANIZATION_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_ORGANIZATION_DETAILS_REQUEST`,
  UPDATE_ORGANIZATION_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_ORGANIZATION_DETAILS_SUCCESS`,
  UPDATE_ORGANIZATION_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_ORGANIZATION_DETAILS_FAILURE`,

};

export const fetchCountry = createAction(ACTION_TYPES.FETCH_COUNTRY);
export const createOrganizationDetails = createAction(ACTION_TYPES.CREATE_ORGANIZATION_DETAILS);
export const updateOrganizationDetails = createAction(ACTION_TYPES.UPDATE_ORGANIZATION_DETAILS);


