import { createAction } from '@reduxjs/toolkit';
import { STATE_REDUCER_KEY } from './constants';

export const ACTION_TYPES = {
  FETCH_COUNTRY: `${STATE_REDUCER_KEY}/FETCH_COUNTRY`,
  FETCH_COUNTRY_REQUEST: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_REQUEST`,
  FETCH_COUNTRY_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_SUCCESS`,
  FETCH_COUNTRY_FAILURE: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_FAILURE`,

  CREATE_ORGANIZATION_DETAILS: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS`,
  CREATE_ORGANIZATION_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_REQUEST`,
  CREATE_ORGANIZATION_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_SUCCESS`,
  CREATE_ORGANIZATION_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_FAILURE`,

  CREATE_JOB_DETAILS: `${STATE_REDUCER_KEY}/CREATE_JOB_DETAILS`,
  CREATE_JOB_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/CREATE_JOB_DETAILS_REQUEST`,
  CREATE_JOB_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_JOB_DETAILS_SUCCESS`,
  CREATE_JOB_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/CREATE_JOB_DETAILS_FAILURE`,

  UPDATE_JOB_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_JOB_DETAILS`,
  UPDATE_JOB_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_JOB_DETAILS_REQUEST`,
  UPDATE_JOB_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_JOB_DETAILS_SUCCESS`,
  UPDATE_JOB_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_JOB_DETAILS_FAILURE`,

  REMOVE_JOB_DETAILS: `${STATE_REDUCER_KEY}/REMOVE_JOB_DETAILS`,
  REMOVE_JOB_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/REMOVE_JOB_DETAILS_REQUEST`,
  REMOVE_JOB_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/REMOVE_JOB_DETAILS_SUCCESS`,
  REMOVE_JOB_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/REMOVE_JOB_DETAILS_FAILURE`,

  FETCH_PROFILE_DETAILS: `${STATE_REDUCER_KEY}/FETCH_PROFILE_DETAILS`,
  FETCH_PROFILE_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_PROFILE_DETAILS_REQUEST`,
  FETCH_PROFILE_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_PROFILE_DETAILS_SUCCESS`,
  FETCH_PROFILE_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_PROFILE_DETAILS_FAILURE`,

  FETCH_REPORT_APPLIED: `${STATE_REDUCER_KEY}/FETCH_REPORT_APPLIED`,
  FETCH_REPORT_APPLIED_REQUEST: `${STATE_REDUCER_KEY}/FETCH_REPORT_APPLIED_REQUEST`,
  FETCH_REPORT_APPLIED_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_REPORT_APPLIED_SUCCESS`,
  FETCH_REPORT_APPLIED_FAILURE: `${STATE_REDUCER_KEY}/FETCH_REPORT_APPLIED_FAILURE`,

  DOWNLAOD_RESUME: `${STATE_REDUCER_KEY}/DOWNLAOD_RESUME`,
  DOWNLAOD_RESUME_REQUEST: `${STATE_REDUCER_KEY}/DOWNLAOD_RESUME_REQUEST`,
  DOWNLAOD_RESUME_SUCCESS: `${STATE_REDUCER_KEY}/DOWNLAOD_RESUME_SUCCESS`,
  DOWNLAOD_RESUME_FAILURE: `${STATE_REDUCER_KEY}/DOWNLAOD_RESUME_FAILURE`

};

export const fetchCountry = createAction(ACTION_TYPES.FETCH_COUNTRY);
export const createOrganizationDetails = createAction(ACTION_TYPES.CREATE_ORGANIZATION_DETAILS);
export const createJobDetails = createAction(ACTION_TYPES.CREATE_JOB_DETAILS);
export const updateJobDetails = createAction(ACTION_TYPES.UPDATE_JOB_DETAILS);
export const removeJobDetails = createAction(ACTION_TYPES.REMOVE_JOB_DETAILS);
export const fetchProfileDetails = createAction(ACTION_TYPES.FETCH_PROFILE_DETAILS);
export const fetchReportAppliedJobDetails = createAction(ACTION_TYPES.FETCH_REPORT_APPLIED);
export const downloadResume = createAction(ACTION_TYPES.DOWNLAOD_RESUME);



