import { createAction } from '@reduxjs/toolkit';
import { STATE_REDUCER_KEY } from './constants';

export const ACTION_TYPES = {
  FETCH_COUNTRY: `${STATE_REDUCER_KEY}/FETCH_COUNTRY`,
  FETCH_COUNTRY_REQUEST: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_REQUEST`,
  FETCH_COUNTRY_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_SUCCESS`,
  FETCH_COUNTRY_FAILURE: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_FAILURE`,

  CREATE_ORGANIZATION_DETAILS: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS`,
  CREATE_ORGANIZATION_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_REQUEST`,
  CREATE_ORGANIZATION_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_SUCCESS`,
  CREATE_ORGANIZATION_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/CREATE_ORGANIZATION_DETAILS_FAILURE`,

  CREATE_JOB_DETAILS: `${STATE_REDUCER_KEY}/CREATE_JOB_DETAILS`,
  CREATE_JOB_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/CREATE_JOB_DETAILS_REQUEST`,
  CREATE_JOB_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_JOB_DETAILS_SUCCESS`,
  CREATE_JOB_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/CREATE_JOB_DETAILS_FAILURE`,

  UPDATE_JOB_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_JOB_DETAILS`,
  UPDATE_JOB_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_JOB_DETAILS_REQUEST`,
  UPDATE_JOB_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_JOB_DETAILS_SUCCESS`,
  UPDATE_JOB_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_JOB_DETAILS_FAILURE`,

  REMOVE_JOB_DETAILS: `${STATE_REDUCER_KEY}/REMOVE_JOB_DETAILS`,
  REMOVE_JOB_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/REMOVE_JOB_DETAILS_REQUEST`,
  REMOVE_JOB_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/REMOVE_JOB_DETAILS_SUCCESS`,
  REMOVE_JOB_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/REMOVE_JOB_DETAILS_FAILURE`,

};

export const fetchCountry = createAction(ACTION_TYPES.FETCH_COUNTRY);
export const createOrganizationDetails = createAction(ACTION_TYPES.CREATE_ORGANIZATION_DETAILS);
export const createJobDetails = createAction(ACTION_TYPES.CREATE_JOB_DETAILS);
export const updateJobDetails = createAction(ACTION_TYPES.UPDATE_JOB_DETAILS);
export const removeJobDetails = createAction(ACTION_TYPES.REMOVE_JOB_DETAILS);



