import { createAction } from '@reduxjs/toolkit';
import { STATE_REDUCER_KEY } from './constants';

export const ACTION_TYPES = {

  FETCH_DASHBOARD_INFO: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_INFO`,
  FETCH_DASHBOARD_INFO_REQUEST: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_INFO_REQUEST`,
  FETCH_DASHBOARD_INFO_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_INFO_SUCCESS`,
  FETCH_DASHBOARD_INFO_FAILURE: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_INFO_FAILURE`,

  FETCH_ADMIN_DASHBOARD_INFO: `${STATE_REDUCER_KEY}/FETCH_ADMIN_DASHBOARD_INFO`,
  FETCH_ADMIN_DASHBOARD_INFO_REQUEST: `${STATE_REDUCER_KEY}/FETCH_ADMIN_DASHBOARD_INFO_REQUEST`,
  FETCH_ADMIN_DASHBOARD_INFO_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_ADMIN_DASHBOARD_INFO_SUCCESS`,
  FETCH_ADMIN_DASHBOARD_INFO_FAILURE: `${STATE_REDUCER_KEY}/FETCH_ADMIN_DASHBOARD_INFO_FAILURE`
};

export const fetchDashboardInfo = createAction(ACTION_TYPES.FETCH_DASHBOARD_INFO);
export const fetchAdminDashboardInfo = createAction(ACTION_TYPES.FETCH_ADMIN_DASHBOARD_INFO);