import { createAction } from '@reduxjs/toolkit';
import { STATE_REDUCER_KEY } from './constants';

export const ACTION_TYPES = {
  FETCH_NOTIFICATIONS: `${STATE_REDUCER_KEY}/FETCH_NOTIFICATIONS`,
  FETCH_NOTIFICATIONS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_NOTIFICATIONS_REQUEST`,
  FETCH_NOTIFICATIONS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_NOTIFICATIONS_SUCCESS`,
  FETCH_NOTIFICATIONS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_NOTIFICATIONS_FAILURE`,

  MARK_READ: `${STATE_REDUCER_KEY}/MARK_READ`,
  MARK_READ_REQUEST: `${STATE_REDUCER_KEY}/MARK_READ_REQUEST`,
  MARK_READ_SUCCESS: `${STATE_REDUCER_KEY}/MARK_READ_SUCCESS`,
  MARK_READ_FAILURE: `${STATE_REDUCER_KEY}/MARK_READ_FAILURE`,

  MARK_ALL_READ: `${STATE_REDUCER_KEY}/MARK_ALL_READ`,
  MARK_ALL_READ_REQUEST: `${STATE_REDUCER_KEY}/MARK_ALL_READ_REQUEST`,
  MARK_ALL_READ_SUCCESS: `${STATE_REDUCER_KEY}/MARK_ALL_READ_SUCCESS`,
  MARK_ALL_READ_FAILURE: `${STATE_REDUCER_KEY}/MARK_ALL_READ_FAILURE`
};

export const fetchNotifications = createAction(ACTION_TYPES.FETCH_NOTIFICATIONS);
export const markNotificationRead = createAction(ACTION_TYPES.MARK_READ);
export const markAllNotificationsRead = createAction(ACTION_TYPES.MARK_ALL_READ);